## Basics

In [71]:
import numpy as np
import pandas as pd

In [72]:
df = pd.DataFrame({
    'Population': [35.467, 63.951, 80.94 , 60.665, 127.061, 64.511, 318.523],
    'GDP': [
        1785387,
        2833687,
        3874437,
        2167744,
        4602367,
        2950039,
        17348075
    ],
    'Surface Area': [
        9984670,
        640679,
        357114,
        301336,
        377930,
        242495,
        9525067
    ],
    'HDI': [
        0.913,
        0.888,
        0.916,
        0.873,
        0.891,
        0.907,
        0.915
    ],
    'Continent': [
        'America',
        'Europe',
        'Europe',
        'Europe',
        'Asia',
        'Europe',
        'America'
    ]
}, columns=['Population', 'GDP', 'Surface Area', 'HDI', 'Continent'])
#The columns attribute is optional,using it to keep the same order.

In [73]:
df

   Population       GDP  Surface Area    HDI Continent
0      35.467   1785387       9984670  0.913   America
1      63.951   2833687        640679  0.888    Europe
2      80.940   3874437        357114  0.916    Europe
3      60.665   2167744        301336  0.873    Europe
4     127.061   4602367        377930  0.891      Asia
5      64.511   2950039        242495  0.907    Europe
6     318.523  17348075       9525067  0.915   America

In [74]:
df.index=[
    'Canada',
    'France',
    'Germany',
    'Italy',
    'Japan',
    'United Kingdom',
    'United States'
]

In [75]:
df

                Population       GDP  Surface Area    HDI Continent
Canada              35.467   1785387       9984670  0.913   America
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [76]:
df.columns

Index(['Population', 'GDP', 'Surface Area', 'HDI', 'Continent'], dtype='str')

In [77]:
df.index

Index(['Canada', 'France', 'Germany', 'Italy', 'Japan', 'United Kingdom',
       'United States'],
      dtype='str')

In [78]:
df.info

<bound method DataFrame.info of                 Population       GDP  Surface Area    HDI Continent
Canada              35.467   1785387       9984670  0.913   America
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America>

In [79]:
df.size

35

In [80]:
df.shape

(7, 5)

In [81]:
df.describe()

       Population           GDP  Surface Area       HDI
count    7.000000  7.000000e+00  7.000000e+00  7.000000
mean   107.302571  5.080248e+06  3.061327e+06  0.900429
std     97.249970  5.494020e+06  4.576187e+06  0.016592
min     35.467000  1.785387e+06  2.424950e+05  0.873000
25%     62.308000  2.500716e+06  3.292250e+05  0.889500
50%     64.511000  2.950039e+06  3.779300e+05  0.907000
75%    104.000500  4.238402e+06  5.082873e+06  0.914000
max    318.523000  1.734808e+07  9.984670e+06  0.916000

In [82]:
df.dtypes

Population      float64
GDP               int64
Surface Area      int64
HDI             float64
Continent           str
dtype: object

## Indexing, Selection and Slicing

In [83]:
df

                Population       GDP  Surface Area    HDI Continent
Canada              35.467   1785387       9984670  0.913   America
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [84]:
df.loc['Canada']

Population       35.467
GDP             1785387
Surface Area    9984670
HDI               0.913
Continent       America
Name: Canada, dtype: object

In [85]:
df.iloc[-1]

Population       318.523
GDP             17348075
Surface Area     9525067
HDI                0.915
Continent        America
Name: United States, dtype: object

In [86]:
df.loc[:,'Population']

Canada             35.467
France             63.951
Germany            80.940
Italy              60.665
Japan             127.061
United Kingdom     64.511
United States     318.523
Name: Population, dtype: float64

In [87]:
df['Population']

Canada             35.467
France             63.951
Germany            80.940
Italy              60.665
Japan             127.061
United Kingdom     64.511
United States     318.523
Name: Population, dtype: float64

In [88]:
df['Population'].to_frame() #Series converted to Data Frame

                Population
Canada              35.467
France              63.951
Germany             80.940
Italy               60.665
Japan              127.061
United Kingdom      64.511
United States      318.523

In [89]:
df.loc[:,['Population','HDI']]

                Population    HDI
Canada              35.467  0.913
France              63.951  0.888
Germany             80.940  0.916
Italy               60.665  0.873
Japan              127.061  0.891
United Kingdom      64.511  0.907
United States      318.523  0.915

In [90]:
df[['Population','HDI']]

                Population    HDI
Canada              35.467  0.913
France              63.951  0.888
Germany             80.940  0.916
Italy               60.665  0.873
Japan              127.061  0.891
United Kingdom      64.511  0.907
United States      318.523  0.915

In [91]:
df[1:3]

         Population      GDP  Surface Area    HDI Continent
France       63.951  2833687        640679  0.888    Europe
Germany      80.940  3874437        357114  0.916    Europe

In [92]:
df.loc['Italy']

Population       60.665
GDP             2167744
Surface Area     301336
HDI               0.873
Continent        Europe
Name: Italy, dtype: object

In [93]:
df.loc['France':'Italy']

         Population      GDP  Surface Area    HDI Continent
France       63.951  2833687        640679  0.888    Europe
Germany      80.940  3874437        357114  0.916    Europe
Italy        60.665  2167744        301336  0.873    Europe

In [94]:
df.loc['France':'Italy','Population']

France     63.951
Germany    80.940
Italy      60.665
Name: Population, dtype: float64

In [95]:
df.loc['France':'Italy',['Population' , 'GDP']]

         Population      GDP
France       63.951  2833687
Germany      80.940  3874437
Italy        60.665  2167744

In [96]:
df

                Population       GDP  Surface Area    HDI Continent
Canada              35.467   1785387       9984670  0.913   America
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [97]:
df.iloc[[0,1,-1]]

               Population       GDP  Surface Area    HDI Continent
Canada             35.467   1785387       9984670  0.913   America
France             63.951   2833687        640679  0.888    Europe
United States     318.523  17348075       9525067  0.915   America

In [98]:
df.iloc[1:3,1]

France     2833687
Germany    3874437
Name: GDP, dtype: int64

In [99]:
df.iloc[1:4,[1,3]]

             GDP    HDI
France   2833687  0.888
Germany  3874437  0.916
Italy    2167744  0.873

In [100]:
df.iloc[1:4, 1:4]

             GDP  Surface Area    HDI
France   2833687        640679  0.888
Germany  3874437        357114  0.916
Italy    2167744        301336  0.873

#### Always use loc and iloc to reduce ambiguity, specially with DataFrames with numeric indexes.

## Conditional selection (boolean arrays)

In [101]:
df

                Population       GDP  Surface Area    HDI Continent
Canada              35.467   1785387       9984670  0.913   America
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [102]:
df['Population']>70

Canada            False
France            False
Germany            True
Italy             False
Japan              True
United Kingdom    False
United States      True
Name: Population, dtype: bool

In [103]:
df.loc[df['Population']>70]

               Population       GDP  Surface Area    HDI Continent
Germany            80.940   3874437        357114  0.916    Europe
Japan             127.061   4602367        377930  0.891      Asia
United States     318.523  17348075       9525067  0.915   America

In [104]:
df[df['Population']>70] # this will give the answer but you can not performe below operation in this.

               Population       GDP  Surface Area    HDI Continent
Germany            80.940   3874437        357114  0.916    Europe
Japan             127.061   4602367        377930  0.891      Asia
United States     318.523  17348075       9525067  0.915   America

In [105]:
df.loc[df['Population']>70,'Population']

Germany           80.940
Japan            127.061
United States    318.523
Name: Population, dtype: float64

In [106]:
df.loc[df['Population']>70,['Population','HDI']]

               Population    HDI
Germany            80.940  0.916
Japan             127.061  0.891
United States     318.523  0.915

## Dropping stuff

In [107]:
df.drop('Canada')

                Population       GDP  Surface Area    HDI Continent
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [108]:
df

                Population       GDP  Surface Area    HDI Continent
Canada              35.467   1785387       9984670  0.913   America
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [109]:
df.drop(['Canada','Italy'])

                Population       GDP  Surface Area    HDI Continent
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [110]:
df.drop(columns=['Population','GDP'])

                Surface Area    HDI Continent
Canada               9984670  0.913   America
France                640679  0.888    Europe
Germany               357114  0.916    Europe
Italy                 301336  0.873    Europe
Japan                 377930  0.891      Asia
United Kingdom        242495  0.907    Europe
United States        9525067  0.915   America

In [111]:

df.drop(['Italy', 'Canada'], axis=0)

                Population       GDP  Surface Area    HDI Continent
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [112]:

df.drop(['Population', 'HDI'], axis=1)

                     GDP  Surface Area Continent
Canada           1785387       9984670   America
France           2833687        640679    Europe
Germany          3874437        357114    Europe
Italy            2167744        301336    Europe
Japan            4602367        377930      Asia
United Kingdom   2950039        242495    Europe
United States   17348075       9525067   America

## Operations

In [113]:

df[['Population', 'GDP']]

                Population       GDP
Canada              35.467   1785387
France              63.951   2833687
Germany             80.940   3874437
Italy               60.665   2167744
Japan              127.061   4602367
United Kingdom      64.511   2950039
United States      318.523  17348075

In [114]:
df[['Population', 'GDP']] / 100

                Population        GDP
Canada             0.35467   17853.87
France             0.63951   28336.87
Germany            0.80940   38744.37
Italy              0.60665   21677.44
Japan              1.27061   46023.67
United Kingdom     0.64511   29500.39
United States      3.18523  173480.75

In [115]:
df

                Population       GDP  Surface Area    HDI Continent
Canada              35.467   1785387       9984670  0.913   America
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [116]:
crisis=pd.Series([-1000000,-0.3],index=['GDP','HDI'])
crisis

GDP   -1000000.0
HDI         -0.3
dtype: float64

In [117]:
df[['GDP','HDI']]

                     GDP    HDI
Canada           1785387  0.913
France           2833687  0.888
Germany          3874437  0.916
Italy            2167744  0.873
Japan            4602367  0.891
United Kingdom   2950039  0.907
United States   17348075  0.915

In [118]:
df[['GDP','HDI']] + crisis

                       GDP    HDI
Canada            785387.0  0.613
France           1833687.0  0.588
Germany          2874437.0  0.616
Italy            1167744.0  0.573
Japan            3602367.0  0.591
United Kingdom   1950039.0  0.607
United States   16348075.0  0.615

## Modifying DataFrames

In [119]:

langs = pd.Series(
    ['French', 'German', 'Italian'],
    index=['France', 'Germany', 'Italy'],
    name='Language'
)

In [120]:
langs

France      French
Germany     German
Italy      Italian
Name: Language, dtype: str

In [121]:
df['Language']=langs

In [122]:
df

                Population       GDP  Surface Area    HDI Continent Language
Canada              35.467   1785387       9984670  0.913   America      NaN
France              63.951   2833687        640679  0.888    Europe   French
Germany             80.940   3874437        357114  0.916    Europe   German
Italy               60.665   2167744        301336  0.873    Europe  Italian
Japan              127.061   4602367        377930  0.891      Asia      NaN
United Kingdom      64.511   2950039        242495  0.907    Europe      NaN
United States      318.523  17348075       9525067  0.915   America      NaN

In [123]:
df['Language']='English'

In [124]:
df

                Population       GDP  Surface Area    HDI Continent Language
Canada              35.467   1785387       9984670  0.913   America  English
France              63.951   2833687        640679  0.888    Europe  English
Germany             80.940   3874437        357114  0.916    Europe  English
Italy               60.665   2167744        301336  0.873    Europe  English
Japan              127.061   4602367        377930  0.891      Asia  English
United Kingdom      64.511   2950039        242495  0.907    Europe  English
United States      318.523  17348075       9525067  0.915   America  English

In [125]:
df.rename(
    columns={
        'HDI':"Human Devlopment Index",
        "Anual Popcorn Consumption":'APC'
    },index={
        "United States":'USA',
        "United Kingdom":'UK',
        'Argentina':'AR'
    }
)

,Population,GDP,Surface Area,Human Devlopment Index,Continent,Language
Canada,35.467,1785387,9984670,0.913,America,English
France,63.951,2833687,640679,0.888,Europe,English
Germany,80.940,3874437,357114,0.916,Europe,English
Italy,60.665,2167744,301336,0.873,Europe,English
Japan,127.061,4602367,377930,0.891,Asia,English
UK,64.511,2950039,242495,0.907,Europe,English
USA,318.523,17348075,9525067,0.915,America,English

In [126]:
df.rename(index=str.upper)

                Population       GDP  Surface Area    HDI Continent Language
CANADA              35.467   1785387       9984670  0.913   America  English
FRANCE              63.951   2833687        640679  0.888    Europe  English
GERMANY             80.940   3874437        357114  0.916    Europe  English
ITALY               60.665   2167744        301336  0.873    Europe  English
JAPAN              127.061   4602367        377930  0.891      Asia  English
UNITED KINGDOM      64.511   2950039        242495  0.907    Europe  English
UNITED STATES      318.523  17348075       9525067  0.915   America  English

In [127]:
df.rename(index=lambda x: x.lower())

                Population       GDP  Surface Area    HDI Continent Language
canada              35.467   1785387       9984670  0.913   America  English
france              63.951   2833687        640679  0.888    Europe  English
germany             80.940   3874437        357114  0.916    Europe  English
italy               60.665   2167744        301336  0.873    Europe  English
japan              127.061   4602367        377930  0.891      Asia  English
united kingdom      64.511   2950039        242495  0.907    Europe  English
united states      318.523  17348075       9525067  0.915   America  English

## Adding values

In [128]:
df.loc['China'] = {'Population': 400.54, 'GDP': 3465723 , 'Continent':'Asia'}
df

                Population       GDP  Surface Area    HDI Continent Language
Canada              35.467   1785387     9984670.0  0.913   America  English
France              63.951   2833687      640679.0  0.888    Europe  English
Germany             80.940   3874437      357114.0  0.916    Europe  English
Italy               60.665   2167744      301336.0  0.873    Europe  English
Japan              127.061   4602367      377930.0  0.891      Asia  English
United Kingdom      64.511   2950039      242495.0  0.907    Europe  English
United States      318.523  17348075     9525067.0  0.915   America  English
China              400.540   3465723           NaN    NaN      Asia      NaN

In [129]:
df.drop('China',inplace=True)

In [130]:
df

                Population       GDP  Surface Area    HDI Continent Language
Canada              35.467   1785387     9984670.0  0.913   America  English
France              63.951   2833687      640679.0  0.888    Europe  English
Germany             80.940   3874437      357114.0  0.916    Europe  English
Italy               60.665   2167744      301336.0  0.873    Europe  English
Japan              127.061   4602367      377930.0  0.891      Asia  English
United Kingdom      64.511   2950039      242495.0  0.907    Europe  English
United States      318.523  17348075     9525067.0  0.915   America  English

## More radical index changes

In [131]:

df.reset_index()

,index,Population,GDP,Surface Area,HDI,Continent,Language
0,Canada,35.467,1785387,9984670.0,0.913,America,English
1,France,63.951,2833687,640679.0,0.888,Europe,English
2,Germany,80.940,3874437,357114.0,0.916,Europe,English
3,Italy,60.665,2167744,301336.0,0.873,Europe,English
4,Japan,127.061,4602367,377930.0,0.891,Asia,English
5,United Kingdom,64.511,2950039,242495.0,0.907,Europe,English
6,United States,318.523,17348075,9525067.0,0.915,America,English

In [132]:

df.set_index('Population')

                 GDP  Surface Area    HDI Continent Language
Population
35.467       1785387     9984670.0  0.913   America  English
63.951       2833687      640679.0  0.888    Europe  English
80.940       3874437      357114.0  0.916    Europe  English
60.665       2167744      301336.0  0.873    Europe  English
127.061      4602367      377930.0  0.891      Asia  English
64.511       2950039      242495.0  0.907    Europe  English
318.523     17348075     9525067.0  0.915   America  English

## Creating columns from other columns

In [133]:
df[['Population','GDP']]

                Population       GDP
Canada              35.467   1785387
France              63.951   2833687
Germany             80.940   3874437
Italy               60.665   2167744
Japan              127.061   4602367
United Kingdom      64.511   2950039
United States      318.523  17348075

In [134]:
df['GDP']/df['Population']

Canada            50339.385908
France            44310.284437
Germany           47868.013343
Italy             35733.025633
Japan             36221.712406
United Kingdom    45729.239975
United States     54464.120330
dtype: float64

In [135]:
df["Per Capita Income"]=df['GDP']/df['Population']

In [136]:
df

,Population,GDP,Surface Area,HDI,Continent,Language,Per Capita Income
Canada,35.467,1785387,9984670.0,0.913,America,English,50339.385908
France,63.951,2833687,640679.0,0.888,Europe,English,44310.284437
Germany,80.940,3874437,357114.0,0.916,Europe,English,47868.013343
Italy,60.665,2167744,301336.0,0.873,Europe,English,35733.025633
Japan,127.061,4602367,377930.0,0.891,Asia,English,36221.712406
United Kingdom,64.511,2950039,242495.0,0.907,Europe,English,45729.239975
United States,318.523,17348075,9525067.0,0.915,America,English,54464.120330

## Statistical info

In [139]:
df.head()

,Population,GDP,Surface Area,HDI,Continent,Language,Per Capita Income
Canada,35.467,1785387,9984670.0,0.913,America,English,50339.385908
France,63.951,2833687,640679.0,0.888,Europe,English,44310.284437
Germany,80.940,3874437,357114.0,0.916,Europe,English,47868.013343
Italy,60.665,2167744,301336.0,0.873,Europe,English,35733.025633
Japan,127.061,4602367,377930.0,0.891,Asia,English,36221.712406

In [138]:
df.describe()

       Population           GDP  Surface Area       HDI  Per Capita Income
count    7.000000  7.000000e+00  7.000000e+00  7.000000           7.000000
mean   107.302571  5.080248e+06  3.061327e+06  0.900429       44952.254576
std     97.249970  5.494020e+06  4.576187e+06  0.016592        6954.983875
min     35.467000  1.785387e+06  2.424950e+05  0.873000       35733.025633
25%     62.308000  2.500716e+06  3.292250e+05  0.889500       40265.998421
50%     64.511000  2.950039e+06  3.779300e+05  0.907000       45729.239975
75%    104.000500  4.238402e+06  5.082873e+06  0.914000       49103.699626
max    318.523000  1.734808e+07  9.984670e+06  0.916000       54464.120330

In [140]:
population=df['Population']

In [141]:
population.min(),population.max()

(np.float64(35.467), np.float64(318.523))

In [142]:
population.sum()

np.float64(751.118)

In [143]:
population.sum()/len(population)

np.float64(107.30257142857144)

In [144]:
population.mean()

np.float64(107.30257142857144)

In [145]:
population.std()

np.float64(97.24996987121581)

In [146]:
population.var()

np.float64(9457.556639952383)

In [148]:
population.median()

np.float64(64.511)

In [150]:
population.describe()

count      7.000000
mean     107.302571
std       97.249970
min       35.467000
25%       62.308000
50%       64.511000
75%      104.000500
max      318.523000
Name: Population, dtype: float64

In [151]:
population.quantile(.25)

np.float64(62.308)

In [152]:
population.quantile([.2, .4, .6, .8, 1])

0.2     61.3222
0.4     64.1750
0.6     74.3684
0.8    117.8368
1.0    318.5230
Name: Population, dtype: float64