## Basics

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
df = pd.read_csv('data/btc-market-price.csv', header=None) # If we do not put header equal to none then it will consider first row has the column names.
df

                       0            1
0    2017-04-02 00:00:00  1099.169125
1    2017-04-03 00:00:00  1141.813000
2    2017-04-04 00:00:00  1141.600363
3    2017-04-05 00:00:00  1133.079314
4    2017-04-06 00:00:00  1196.307937
..                   ...          ...
360  2018-03-28 00:00:00  7960.380000
361  2018-03-29 00:00:00  7172.280000
362  2018-03-30 00:00:00  6882.531667
363  2018-03-31 00:00:00  6935.480000
364  2018-04-01 00:00:00  6794.105000

[365 rows x 2 columns]

In [4]:
df.head()

                     0            1
0  2017-04-02 00:00:00  1099.169125
1  2017-04-03 00:00:00  1141.813000
2  2017-04-04 00:00:00  1141.600363
3  2017-04-05 00:00:00  1133.079314
4  2017-04-06 00:00:00  1196.307937

In [5]:
df.columns=['Time_Stamp','Price']

In [6]:
df

              Time_Stamp        Price
0    2017-04-02 00:00:00  1099.169125
1    2017-04-03 00:00:00  1141.813000
2    2017-04-04 00:00:00  1141.600363
3    2017-04-05 00:00:00  1133.079314
4    2017-04-06 00:00:00  1196.307937
..                   ...          ...
360  2018-03-28 00:00:00  7960.380000
361  2018-03-29 00:00:00  7172.280000
362  2018-03-30 00:00:00  6882.531667
363  2018-03-31 00:00:00  6935.480000
364  2018-04-01 00:00:00  6794.105000

[365 rows x 2 columns]

In [7]:
df.shape

(365, 2)

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Time_Stamp  365 non-null    str
 1   Price       365 non-null    float64
dtypes: float64(1), str(1)
memory usage: 5.8 KB

In [9]:
df.tail()

              Time_Stamp        Price
360  2018-03-28 00:00:00  7960.380000
361  2018-03-29 00:00:00  7172.280000
362  2018-03-30 00:00:00  6882.531667
363  2018-03-31 00:00:00  6935.480000
364  2018-04-01 00:00:00  6794.105000

In [10]:
df.dtypes

Time_Stamp        str
Price         float64
dtype: object

In [11]:
pd.to_datetime(df['Time_Stamp']).head()

0   2017-04-02
1   2017-04-03
2   2017-04-04
3   2017-04-05
4   2017-04-06
Name: Time_Stamp, dtype: datetime64[us]

In [12]:
df['Time_Stamp']=pd.to_datetime(df['Time_Stamp'])

In [13]:
df

    Time_Stamp        Price
0   2017-04-02  1099.169125
1   2017-04-03  1141.813000
2   2017-04-04  1141.600363
3   2017-04-05  1133.079314
4   2017-04-06  1196.307937
..         ...          ...
360 2018-03-28  7960.380000
361 2018-03-29  7172.280000
362 2018-03-30  6882.531667
363 2018-03-31  6935.480000
364 2018-04-01  6794.105000

[365 rows x 2 columns]

In [14]:
df.dtypes

Time_Stamp    datetime64[us]
Price                float64
dtype: object

In [15]:
df.set_index('Time_Stamp', inplace=True)

In [16]:
df.head()

                  Price
Time_Stamp
2017-04-02  1099.169125
2017-04-03  1141.813000
2017-04-04  1141.600363
2017-04-05  1133.079314
2017-04-06  1196.307937

In [17]:
df.loc['2017-09-19']

Price    3943.413333
Name: 2017-09-19 00:00:00, dtype: float64

## Putting everything together

In [18]:
df=pd.read_csv('data/btc-market-price.csv',header=None)
df.columns=['Time_Stamp','Price']
df['Time_Stamp']=pd.to_datetime(df['Time_Stamp'])
df.set_index('Time_Stamp',inplace=True)

In [19]:
df.head()

                  Price
Time_Stamp
2017-04-02  1099.169125
2017-04-03  1141.813000
2017-04-04  1141.600363
2017-04-05  1133.079314
2017-04-06  1196.307937

In [20]:
df=pd.read_csv(
    'data/btc-market-price.csv',
    header=None,
    names=['Timestamp','Price'],
    index_col=0,
    parse_dates=True
)
df

                  Price
Timestamp
2017-04-02  1099.169125
2017-04-03  1141.813000
2017-04-04  1141.600363
2017-04-05  1133.079314
2017-04-06  1196.307937
...                 ...
2018-03-28  7960.380000
2018-03-29  7172.280000
2018-03-30  6882.531667
2018-03-31  6935.480000
2018-04-01  6794.105000

[365 rows x 1 columns]